platform :ios, '9.0'

target 'Example' do
  use_frameworks!
  pod 'Tracker', :path => '../'
  pod 'SwiftGen', '~> 6.0'
  
  script_phase :name => 'SwiftGen', :script => '${SRCROOT}/../Scripts/event_generated_code.sh', :execution_position  => :before_compile
  
end
